ren	calculationAnalysis.xlsx	BaggBillAnalysis.xlsx
ren	calculationResult.txt	BaggBillResult.txt
ren	calculationResult1.txt	BaggBillResult1.txt
ren	calculationResult10.txt	BaggBillResult10.txt
ren	calculationResult11.txt	BaggBillResult11.txt
ren	calculationResult12.txt	BaggBillResult12.txt
ren	calculationResult13.txt	BaggBillResult13.txt
ren	calculationResult14.txt	BaggBillResult14.txt
ren	calculationResult15.txt	BaggBillResult15.txt
ren	calculationResult16.txt	BaggBillResult16.txt
ren	calculationResult17.txt	BaggBillResult17.txt
ren	calculationResult18.txt	BaggBillResult18.txt
ren	calculationResult19.txt	BaggBillResult19.txt
ren	calculationResult2.txt	BaggBillResult2.txt
ren	calculationResult20.txt	BaggBillResult20.txt
ren	calculationResult21.txt	BaggBillResult21.txt
ren	calculationResult22.txt	BaggBillResult22.txt
ren	calculationResult23.txt	BaggBillResult23.txt
ren	calculationResult24.txt	BaggBillResult24.txt
ren	calculationResult25.txt	BaggBillResult25.txt
ren	calculationResult26.txt	BaggBillResult26.txt
ren	calculationResult27.txt	BaggBillResult27.txt
ren	calculationResult28.txt	BaggBillResult28.txt
ren	calculationResult29.txt	BaggBillResult29.txt
ren	calculationResult3.txt	BaggBillResult3.txt
ren	calculationResult30.txt	BaggBillResult30.txt
ren	calculationResult4.txt	BaggBillResult4.txt
ren	calculationResult5.txt	BaggBillResult5.txt
ren	calculationResult6.txt	BaggBillResult6.txt
ren	calculationResult7.txt	BaggBillResult7.txt
ren	calculationResult8.txt	BaggBillResult8.txt
ren	calculationResult9.txt	BaggBillResult9.txt
